cabal-version:      3.4
name:               ding-dong
version:            0.1.0.0

synopsis:           Nostr web client
license:            MIT
license-file:       LICENSE

author:             Branislav branko1755@proton.me

build-type:         Simple
extra-doc-files:    CHANGELOG.md


common warnings
    ghc-options: -Wall

library
    import:           warnings
    exposed-modules:
                      Nostr.Request
                      Nostr.Response
                      Nostr.Relay
                      Nostr.Filter
                      Nostr.Kind
                      Nostr.Event
                      Nostr.HashableEvent
                      Nostr.Keys
                      Nostr.Profile
                      Nostr.WebSocket
                      Nostr.Network
                      Nostr.RelayPool
                      Nostr.Log
                      Nostr.Reaction
                      Nostr.PagedChronologicalEvents
                      PeriodicLoader
                      ReactionsLoader
                      ProfilesLoader
                      ProfilesLoader.Types
                      MyCrypto
                      DingDong
                      Contacts
                      MisoSubscribe
                      SubscriptionUtils
                      ModelAction
                      BechUtils
                      ContentUtils
                      Utils
                      StoredRelay
                      Miso.Components.LoadingBar
                      Miso.Components.ImageWithMouseActions
                      Miso.Components.DumbTwo
                      Miso.Components.Post
                      Miso.Components.AuthorInfoPanel
                      Miso.Components.SidePanel


    build-depends:    base >=4.20.0.0
                      , secp256k1-haskell
                      , miso
                      , aeson
                      , jsaddle
                      , jsaddle-dom
                      , bytestring
                      , vector
                      , cryptohash-sha256
                      , base16
                      , data-default
                      , text < 2.1.2
                      , time
                      , containers
                      , string-conversions
                      , datetime
                      , optics
                      , stm
                      , mtl
                      , intervals
                      , entropy
                      , bech32
                      , extra
                      , scientific
                      , network-uri
                      , raw-strings-qq
                      , transformers
                      , hashable
    hs-source-dirs:   src
    default-language: Haskell2010

executable nostr-wasm
  hs-source-dirs: app
  main-is:
     App.hs
  if arch(wasm32)
    ghc-options: -no-hs-main -optl-mexec-model=reactor "-optl-Wl,--export=hs_start"
  else
    ghc-options: -main-is App.main -prof -fprof-auto
  build-depends:
      ding-dong
    , aeson
    , miso
    , containers
    , transformers
    , jsaddle
    , jsaddle-wasm
    , ghc-experimental
    , base
    , mtl
    , optics

  if !arch(wasm32)
      build-depends:
        jsaddle-warp

library test-relay
  hs-source-dirs: test/relay/
  exposed-modules:  Relay.RelayServer
                    Relay.Request
                    Relay.Database
  ghc-options: -threaded
  default-language: Haskell2010

  build-depends:
    base,
    websockets,
    text < 2.1.2,
    ding-dong,
    aeson,
    vector,
    mtl,
    containers,
    optics,
    base16,
    bytestring,
    time,
    datetime,
    miso,
    hslogger,
    directory

executable websockets-server
  hs-source-dirs:   test/
  main-is:          RunRelay.hs
  ghc-options: -main-is RunRelay -threaded
  default-language: Haskell2010

  build-depends:
    base,
    websockets,
    text < 2.1.2,
    ding-dong,
    aeson,
    vector,
    mtl,
    containers,
    optics,
    base16,
    bytestring,
    time,
    datetime,
    miso,
    hslogger,
    directory,
    ding-dong:test-relay,

executable test
  hs-source-dirs:   test
  main-is:          MainTest.hs
  other-modules:    Test
                    TestEvents
                    Puppet
                    Configuration
                    UnitTest.PeriodicLoader
  if arch(wasm32)
    ghc-options: -no-hs-main -optl-mexec-model=reactor "-optl-Wl,--export=hs_start"
  else
    ghc-options: -main-is MainTest -threaded -Wall
  default-language: Haskell2010

  build-depends:
    base,
    jsaddle,
    jsaddle-wasm,
    jsaddle-warp,
    ghc-experimental,
    text < 2.1.2,
    ding-dong,
    mtl,
    containers,
    optics,
    time,
    datetime,
    process,
    miso,
    aeson,
    bytestring,
    http-conduit,
    http-types,
    vector,
    websockets,
    async,
    extra,
    hslogger,
    directory,
    unix,
    ding-dong:test-relay,
